### ISSUE TITLE
Invalid SSL cert

### ISSUE THREAD

**Issue by getaaron** [breedx2/mcor#6]
churchofrobotron.com uses an invalid security certificate.
 
The certificate is not trusted because it is self-signed.

**Comment by breedx2** [comment]
This is an important point -- trust is one aspect of our humanity that the evil, disgusting ROBOTRONS will never be able to comprehend.  It is a characteristic that sets us apart from the machines...and it is one that could potentially give us advantage.  The bots will forever strive to confuse and obliterate us -- the early stages of this could include spreading misinformation in our honorable name or simply observing human interactions with the church website.  We must not stand by and allow the bots to take hold.  We cannot (and refuse to!) allow ourselves to be weakened and our message cheapened by this "self signed certificate".  We must not open ourselves up to the possibility of a "man in the middle" (really BOT IN THE MIDDLE) attacks.

We must be vigilant, brothers and sisters.  We must not let down our guard.

It is only through a well established chain of trust that we can keep the ROBOTRONS at bay. 

To help secure the website, I will assign this to @bzztbomb, as I believe that he has greater knowledge and trusted access to the necessary resources to secure our certificate and ensure trust is restored.  Perhaps it would be somewhat trivial for him to set up  to use [certbot](https://certbot.eff.org/) to use [letsencrypt](https://letsencrypt.org/).

**Comment by bzztbomb** [comment]
@getaaron @breedx2 

Despite my reservations of allowing machines decide if members of the human family trust each others communications I have enabled SSL.  Feel confident in the fact that when [https://churchofrobotron.com](https://churchofrobotron.com)/ tells you to take up the two eight ways, that this message is coming from a devotee to our mutant savior!  

We should all take a moment today to ponder futility and rejoice in error!
